=== onap/archive-ccsdk-sli-core/sli/common/src/main/resources/svclogic.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openecomp.org/sdnc/svclogic" xmlns="http://www.openecomp.org/sdnc/svclogic">

	<xsd:simpleType name="modeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="sync" />
			<xsd:enumeration value="async" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:group name="node">
		<xsd:choice>
			<xsd:element ref="block" />
			<xsd:element ref="is-available" />
			<xsd:element ref="exists" />
			<xsd:element ref="reserve" />
			<xsd:element ref="release" />
			<xsd:element ref="allocate" />
			<xsd:element ref="get-resource" />
			<xsd:element ref="configure" />
			<xsd:element ref="return" />
			<xsd:element ref="switch" />
			<xsd:element ref="record" />
			<xsd:element ref="save" />
			<xsd:element ref="for" />
			<xsd:element ref="set" />
			<xsd:element ref="execute" />
			<xsd:element ref="delete" />
			<xsd:element ref="update" />
			<xsd:element ref="call" />
			<xsd:element ref="notify" />
			<xsd:element ref="break" />
			<xsd:element ref="while" />
		</xsd:choice>
	</xsd:group>

	<xsd:element name="service-logic">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="module" use="required" type="xsd:string" />
			<xsd:attribute name="version" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="method">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="rpc" use="required" type="xsd:string" />
			<xsd:attribute name="mode" use="optional" type="modeType" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="block">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="atomic" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="is-available">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="exists">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="outcome">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ref" use="optional" type="xsd:string" />
			<xsd:attribute name="value" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="reserve">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="select" use="optional" type="xsd:string" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="release">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="record">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="allocate">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="required" type="xsd:string" />
			<xsd:attribute name="pfx" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="get-resource">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="local-only" use="optional" type="xsd:boolean" />
			<xsd:attribute name="order-by" use="optional" type="xsd:string" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
			<!-- force is retired and does not do anything -->
			<xsd:attribute name="force" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="configure">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="adaptor" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="required" type="xsd:string" />
			<xsd:attribute name="activate" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="parameter">
		<xsd:complexType>
			<xsd:attribute name="name" use="required" type="xsd:string" />
			<xsd:attribute name="value" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="return">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="status" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="switch">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="test" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="save">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="force" use="optional" type="xsd:boolean" />
			<xsd:attribute name="local-only" use="optional" type="xsd:boolean" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="delete">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<!-- force is retired and does not do anything -->
			<xsd:attribute name="force" use="optional" type="xsd:string" />
			<!-- local-only is retired and does not do anything -->
			<xsd:attribute name="local-only" use="optional" type="xsd:string" />
			<!-- pfx is retired and does not do anything -->
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="for">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="atomic" use="optional" type="xsd:boolean" />
			<xsd:attribute name="index" use="required" type="xsd:string" />
			<xsd:attribute name="start" use="required" type="xsd:string" />
			<xsd:attribute name="end" use="required" type="xsd:string" />
			<xsd:attribute name="silentFailure" use="optional" type="xsd:boolean" default="false" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="set">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="only-if-unset" use="optional"
				type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="execute">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="method" use="required" type="xsd:string" />
			<xsd:attribute name="emitsOutcome" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="update">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="force" use="optional" type="xsd:boolean" />
			<xsd:attribute name="local-only" use="optional" type="xsd:boolean" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="call">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="module" use="optional" type="xsd:string" />
			<xsd:attribute name="rpc" use="required" type="xsd:string" />
			<xsd:attribute name="version" use="optional" type="xsd:string" />
			<xsd:attribute name="mode" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="notify">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="optional" type="xsd:string" />
			<xsd:attribute name="resource" use="optional" type="xsd:string" />
			<xsd:attribute name="action" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<!-- force is retired and does not do anything -->
			<xsd:attribute name="force" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="break">
		<xsd:complexType />
	</xsd:element>

	<xsd:element name="while">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="test" use="required" type="xsd:string" />
			<xsd:attribute name="do" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== onap/archive-ccsdk-sli-core/sli/impl/src/test/resources/copyValues.xml
<service-logic
    xmlns='http://www.onap.org/sdnc/svclogic'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.onap.org/sdnc/svclogic ./svclogic.xsd' module='TEST-DG' version='1.0.0'>
    <method rpc='test-dg' mode='sync'>
        <block>
            <set>
                <parameter name='si.field1' value='1' />
                <parameter name='si.field2' value='2' />
                <parameter name='si.field3' value='3' />
            </set>
            <set>
                <parameter name='rootTwo.' value='si.' />
            </set>
        </block>
    </method>
</service-logic>

=== onap/archive-ccsdk-sli-core/sli/common/src/test/resources/neutron_logic_v10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ============LICENSE_START=======================================================
  openECOMP : SDN-C
  ================================================================================
  Copyright (C) 2017 AT&T Intellectual Property. All rights
  						reserved.
  ================================================================================
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  ============LICENSE_END=========================================================
  -->


<service-logic xmlns="http://www.openecomp.org/sdnc/svclogic"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openecomp.org/sdnc/svclogic ./svclogic.xsd"
    module="neutron" version="1.0.0">

    <method rpc="canCreateNetwork" mode="sync">
        <return status="success">
            <parameter name="error-code" value="200" />
        </return>
    </method>

    <method rpc="networkCreated" mode="sync">
        <switch test="`(length($network.segment[0].provider-physical-network) >= 5) and (substr($network.segment[0].provider-physical-network,0,5) == 'dvspg')`">
            <outcome value="true">
                <block>
                <set>
                  <parameter name="vlanlist" value="`$network.segment[0].provider-segmentation-id`"/>
                </set>
                <for index="i" start="1" end="`$network.num-segments`">
                  <set>
                    <parameter name="vlanlist" value="`$vlanlist+','+$network.segment[$i].provider-segmentation-id`"/>
                  </set>
                </for>

                </block>
            </outcome>
            <outcome value="Other">
                <return status="success">
                    <parameter name="error-code" value="200"/>
                </return>
            </outcome>
        </switch>
    </method>

</service-logic>

=== onap/archive-ccsdk-sli-core/sli/common/src/test/resources/clearSingleSubArrayValues.xml
<service-logic
    xmlns='http://www.onap.org/sdnc/svclogic'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.onap.org/sdnc/svclogic ./svclogic.xsd' module='TEST-DG' version='1.0.0'>
    <method rpc='test-dg' mode='sync'>
        <block>
            <set>
                <parameter name='tmp.si[0].field1' value='1' /> 
                <parameter name='tmp.si[1].field2' value='2' /> 
                <parameter name='tmp.si[2].field3' value='3' /> 
                <parameter name='tmp.si_length' value='3' /> 
                <parameter name='tmp.si[0].subarray[0]' value='a' /> 
                <parameter name='tmp.si[0].subarray[1]' value='b' /> 
                <parameter name='tmp.si[0].subarray[2]' value='c' /> 
                <parameter name='tmp.si[0].subarray_length' value='3' /> 
                <parameter name='tmp.si[1].subarray[0]' value='x' /> 
                <parameter name='tmp.si[1].subarray[1]' value='y' /> 
                <parameter name='tmp.si[1].subarray[2]' value='z' /> 
                <parameter name='tmp.si[1].subarray_length' value='3' /> 
                <parameter name='search1' value='6' /> 
                <parameter name='simonSays' value='KeepMe!' /> 
            </set>
            <set>
                <parameter name='tmp.si[0].subarray[1]' value='' />
            </set>
        </block>
    </method>
</service-logic>

=== onap/archive-ccsdk-sli-core/sli/common/src/test/resources/ReleasePortSvcLogic_v101.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ============LICENSE_START=======================================================
  openECOMP : SDN-C
  ================================================================================
  Copyright (C) 2017 AT&T Intellectual Property. All rights
  						reserved.
  ================================================================================
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  ============LICENSE_END=========================================================
  -->


<service-logic xmlns="http://www.openecomp.org/sdnc/svclogic"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openecomp.org/sdnc/svclogic ./svclogic.xsd"
    module="ase" version="1.0.1">

    <!-- Updated release port logic : deactivate the released port on the EMT -->
    <method rpc="ase-release-port-request" mode="sync">
        <exists plugin="org.openecomp.sdnc.sli.resource.sample.SampleResource"
            resource="ase-evc" key="uni-circuit-id  == $uni-circuit-id">

            <outcome value="true">
                <return status="failure">
                    <parameter name="error-code" value="1130" />
                    <parameter name="error-message"
                        value="Cannot release port - used in existing EVC" />
                </return>
            </outcome>
            <outcome value="false">
                <release plugin="org.openecomp.sdnc.sli.resource.sample.SampleResource"
                    resource="ase-port" key="uni-circuit-id == $uni-circuit-id">
                    <outcome value="success">
                        <configure adaptor="org.openecomp.sdnc.sli.adaptor.emt.EmtAdaptor"
                            key="$uni-circuit-id" activate="false">

                            <outcome value="success">
                                <block>
                                    <record plugin="org.openecomp.sdnc.sli.recording.FileRecorder">
                                        <parameter name="file" value="/tmp/sample_r1.log" />
                                        <parameter name="field1" value="__TIMESTAMP__" />
                                        <parameter name="field2" value="RELEASED" />
                                        <parameter name="field3" value="$uni-circuit-id" />
                                    </record>
                                    <return status="success">
                                        <parameter name="uni-circuit-id" value="$asePort.uni_circuit_id" />
                                    </return>
                                </block>
                            </outcome>
                            <outcome value="Other">
                                <return status="failure">
                                    <parameter name="error-code" value="1130" />
                                    <parameter name="error-message"
                                        value="Error encountered trying to de-activate port" />
                                </return>
                            </outcome>
                        </configure>
                    </outcome>

                    <outcome value="not-found">
                        <return status="failure">
                            <parameter name="error-code" value="1110" />
                            <parameter name="error-message" value="No port found for this uni-circuit-id" />
                        </return>
                    </outcome>

                    <outcome value="Other">
                        <return status="failure">
                            <parameter name="error-code" value="1130" />
                            <parameter name="error-message"
                                value="Error encountered trying to release port" />
                        </return>
                    </outcome>
                </release>
            </outcome>
        </exists>
    </method>

</service-logic>

=== onap/archive-ccsdk-sli-core/sli/common/src/test/resources/EvcActivateSvcLogic_v100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ============LICENSE_START=======================================================
  openECOMP : SDN-C
  ================================================================================
  Copyright (C) 2017 AT&T Intellectual Property. All rights
  						reserved.
  ================================================================================
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  ============LICENSE_END=========================================================
  -->


<service-logic xmlns="http://www.openecomp.org/sdnc/svclogic"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openecomp.org/sdnc/svclogic ./svclogic.xsd"
    module="ase" version="1.0.0">


    <method rpc="ase-evc-activation" mode="sync">
        <configure adaptor="org.openecomp.sdnc.sli.adaptor.emt.EmtAdaptor"
            key="$evc-name" activate="true">
            <parameter name="circuit.name" value="$evc-name" />
            <parameter name="topology" value="$topology" />
            <parameter name="leg1.uniCircuitId" value="$evc-leg[0].evc-access-name" />
            <parameter name="leg2.uniCircuitId" value="$evc-leg[1].evc-access-name" />
            <outcome value="success">
                <return status="success" />
            </outcome>
            <outcome value="already-active">
                <return status="failure">
                    <parameter name="error-code" value="1590" />
                    <parameter name="error-message" value="`Circuit already active`" />
                </return>
            </outcome>
            <outcome value="Other">
                <return status="failure">
                    <parameter name="error-code" value="1542" />
                    <parameter name="error-message" value="Activation failure" />
                </return>
            </outcome>
        </configure>
    </method>

    <method rpc="ase-evc-disconnect-request" mode="sync">
        <configure adaptor="org.openecomp.sdnc.sli.adaptor.emt.EmtAdaptor"
            key="$evc-name" activate="false">
            <outcome value="success">
                <return status="success" />
            </outcome>

            <outcome value="Other">
                <return status="failure">
                    <parameter name="error-code" value="1542" />
                    <parameter name="error-message" value="De-activation failure" />
                </return>
            </outcome>
        </configure>
    </method>


</service-logic>

=== onap/archive-ccsdk-sli-core/sli/parser/src/test/resources/clearSingleArrayValues.xml
<service-logic
    xmlns='http://www.onap.org/sdnc/svclogic'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.onap.org/sdnc/svclogic ./svclogic.xsd' module='TEST-DG' version='1.0.0'>
    <method rpc='test-dg' mode='sync'>
        <block>
            <set>
                <parameter name='si[0].field1' value='1' />
                <parameter name='si[1].field2' value='2' />
                <parameter name='si[2].field3' value='3' />
                <parameter name='si_length' value='3' />
                <parameter name='si[0].subarray[0]' value='a' /> 
                <parameter name='si[0].subarray[1]' value='b' /> 
                <parameter name='si[0].subarray[2]' value='c' /> 
                <parameter name='si[0].subarray_length' value='3' />
                <parameter name='search1' value='6' />
                <parameter name='simonSays' value='KeepMe!' />
            </set>
            <set>
                <parameter name='si[0].' value='' />
            </set>
        </block>
    </method>
</service-logic>

=== onap/archive-ccsdk-sli-core/sliapi/provider/src/test/resources/sli_forNode.xml
<!--
  ============LICENSE_START=======================================================
  openECOMP : SDN-C
  ================================================================================
  Copyright (C) 2017 AT&T Intellectual Property. All rights
  							reserved.
  ================================================================================
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  ============LICENSE_END=========================================================
-->

<service-logic xmlns="http://www.onap.org/sdnc/svclogic"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.onap.org/sdnc/svclogic ./svclogic.xsd" module="test" version="1" >

    <method rpc="forNode" mode="sync">
        <block>
            <for index="1" start="true" end="3"><configure adaptor="com.att.sdnctl.sli.adaptor.ncs.ncsAdaptor" key="SNIIR" activate="true"><parameter name="input.request-id" value="`$eipam-ip-block.request-id`"/><parameter name="input.source" value="SDNC"/><parameter name="input.ptnii-name" value="`$eipam-ip-block.ptnii-name`"/><parameter name="input.ip-address" value="`$eipam-ip-block.ip-address`"/><parameter name="input.mask" value="`$eipam-ip-block.prefix-length`"/><outcome value="success">
            </outcome><outcome value="Other">
            </outcome></configure></for>
        </block>
    </method>
</service-logic>
