=== onap/archive-ccsdk-sli-core/sli/common/src/main/resources/svclogic.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openecomp.org/sdnc/svclogic" xmlns="http://www.openecomp.org/sdnc/svclogic">

	<xsd:simpleType name="modeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="sync" />
			<xsd:enumeration value="async" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:group name="node">
		<xsd:choice>
			<xsd:element ref="block" />
			<xsd:element ref="is-available" />
			<xsd:element ref="exists" />
			<xsd:element ref="reserve" />
			<xsd:element ref="release" />
			<xsd:element ref="allocate" />
			<xsd:element ref="get-resource" />
			<xsd:element ref="configure" />
			<xsd:element ref="return" />
			<xsd:element ref="switch" />
			<xsd:element ref="record" />
			<xsd:element ref="save" />
			<xsd:element ref="for" />
			<xsd:element ref="set" />
			<xsd:element ref="execute" />
			<xsd:element ref="delete" />
			<xsd:element ref="update" />
			<xsd:element ref="call" />
			<xsd:element ref="notify" />
			<xsd:element ref="break" />
			<xsd:element ref="while" />
		</xsd:choice>
	</xsd:group>

	<xsd:element name="service-logic">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="module" use="required" type="xsd:string" />
			<xsd:attribute name="version" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="method">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="rpc" use="required" type="xsd:string" />
			<xsd:attribute name="mode" use="optional" type="modeType" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="block">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="atomic" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="is-available">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="exists">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="outcome">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ref" use="optional" type="xsd:string" />
			<xsd:attribute name="value" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="reserve">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="select" use="optional" type="xsd:string" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="release">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="record">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="allocate">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="required" type="xsd:string" />
			<xsd:attribute name="pfx" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="get-resource">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="local-only" use="optional" type="xsd:boolean" />
			<xsd:attribute name="order-by" use="optional" type="xsd:string" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
			<!-- force is retired and does not do anything -->
			<xsd:attribute name="force" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="configure">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="adaptor" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="required" type="xsd:string" />
			<xsd:attribute name="activate" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="parameter">
		<xsd:complexType>
			<xsd:attribute name="name" use="required" type="xsd:string" />
			<xsd:attribute name="value" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="return">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="status" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="switch">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="test" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="save">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="force" use="optional" type="xsd:boolean" />
			<xsd:attribute name="local-only" use="optional" type="xsd:boolean" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="delete">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<!-- force is retired and does not do anything -->
			<xsd:attribute name="force" use="optional" type="xsd:string" />
			<!-- local-only is retired and does not do anything -->
			<xsd:attribute name="local-only" use="optional" type="xsd:string" />
			<!-- pfx is retired and does not do anything -->
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="for">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="atomic" use="optional" type="xsd:boolean" />
			<xsd:attribute name="index" use="required" type="xsd:string" />
			<xsd:attribute name="start" use="required" type="xsd:string" />
			<xsd:attribute name="end" use="required" type="xsd:string" />
			<xsd:attribute name="silentFailure" use="optional" type="xsd:boolean" default="false" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="set">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="only-if-unset" use="optional"
				type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="execute">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="method" use="required" type="xsd:string" />
			<xsd:attribute name="emitsOutcome" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="update">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="required" type="xsd:string" />
			<xsd:attribute name="resource" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<xsd:attribute name="force" use="optional" type="xsd:boolean" />
			<xsd:attribute name="local-only" use="optional" type="xsd:boolean" />
			<xsd:attribute name="pfx" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="call">
		<xsd:complexType>
			<xsd:sequence>
				<!-- This node does not actually read from parameters -->
				<xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="module" use="optional" type="xsd:string" />
			<xsd:attribute name="rpc" use="required" type="xsd:string" />
			<xsd:attribute name="version" use="optional" type="xsd:string" />
			<xsd:attribute name="mode" use="required" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="notify">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="outcome" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="plugin" use="optional" type="xsd:string" />
			<xsd:attribute name="resource" use="optional" type="xsd:string" />
			<xsd:attribute name="action" use="required" type="xsd:string" />
			<xsd:attribute name="key" use="optional" type="xsd:string" />
			<!-- force is retired and does not do anything -->
			<xsd:attribute name="force" use="optional" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="break">
		<xsd:complexType />
	</xsd:element>

	<xsd:element name="while">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="node" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="test" use="required" type="xsd:string" />
			<xsd:attribute name="do" use="optional" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== onap/archive-ccsdk-sli-core/sliapi/springboot/src/test/resources/DEMO_DEMO.xml
<service-logic
    xmlns='http://www.onap.org/sdnc/svclogic'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.onap.org/sdnc/svclogic ./svclogic.xsd' module='DEMO' version='1'>
    <method rpc='DEMO' mode='sync'>
        <block>
            <record plugin="org.onap.ccsdk.sli.core.sli.recording.Slf4jRecorder">
                <parameter name="logger" value="message-log" />
                <parameter name="level" value="error" />
                <parameter name="field1" value="Slf4jRecorder must be working!" />
            </record>
            <execute plugin="org.onap.ccsdk.sli.core.slipluginutils.SliPluginUtils" method="generateUUID">
                <parameter name="ctx-destination" value="requestID" />
            </execute>
            <execute plugin="org.onap.ccsdk.sli.core.slipluginutils.SliStringUtils" method="contains" emitsOutcome='true' >
                <parameter name="source" value="TEAM" />
                <parameter name="target" value="I" />
            </execute>
            <execute plugin="org.onap.ccsdk.sli.plugins.prop.PropertiesNode" method="readProperties" >
                <parameter name="fileName" value="%SDNC_CONFIG_DIR%/aaf.properties" />
                <parameter name="contextPrefix" value="tmp.props" />
            </execute>
            <execute plugin="org.onap.ccsdk.sli.plugins.restapicall.RestapiCallNode" method="sendRequest">
                <parameter name="restapiUrl" value="http://127.0.0.1:8080/restconf/config/SLI-API:test-results/"/>
                <parameter name="restapiUser" value="admin"/>
                <parameter name="restapiPassword" value="test"/>
                <parameter name="format" value="json" />
                <parameter name="httpMethod" value="get" />
                <parameter name="responsePrefix" value="restapi-result" />
            </execute>
            <return status='success'>
                <parameter name='' value='' />
            </return>
        </block>
    </method>
</service-logic>

=== onap/archive-ccsdk-sli-core/sli/provider/src/test/resources/l3sdn_logic_v10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ============LICENSE_START=======================================================
    ONAP : CCSDK ================================================================================
    Copyright (C) 2017 AT&T Intellectual Property. All rights reserved. ================================================================================
    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required
    by applicable law or agreed to in writing, software distributed under the
    License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
    OF ANY KIND, either express or implied. See the License for the specific
    language governing permissions and limitations under the License. ============LICENSE_END========================================================= -->


<service-logic xmlns="http://www.onap.org/sdnc/svclogic"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.onap.org/sdnc/svclogic ./svclogic.xsd"
    module="neutron" version="1.0.0">

    <method rpc="canCreateNetwork" mode="sync">
        <return status="success">
            <parameter name="error-code" value="200" />
        </return>
    </method>

    <method rpc="switchTester" mode="sync">

        <switch test="`$test-value`">
            <outcome value="">
                <return status="success">
                    <parameter name="visited-outcome" value="empty string" />
                </return>
            </outcome>
            <outcome value="Other">
                <return status="success">
                    <parameter name="visited-outcome" value="Other" />
                </return>
            </outcome>
        </switch>


    </method>

    <method rpc="forRecordTester" mode="sync">
        <for index="i" start="0" end="1">
            <record plugin="org.onap.ccsdk.sli.core.sli.provider.DummyRecorder">
                <parameter name="level" value="INFO"/>
                <parameter name="field1" value="`forRecordTester message $i`"/>
            </record>
        </for>
    </method>

    <method rpc="resourceTester" mode="sync">
        <block>
            <set>
                <parameter name='resource-plugin'
                    value='org.onap.ccsdk.sli.core.sli.provider.DummyResource' />
            </set>

            <save plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'">
               <parameter name="sample-key" value="resourceTester.status"/>
               <parameter name="sample-value" value="FAILED"/>
            </save>

            <update plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'">
               <parameter name="sample-key" value="resourceTester.status"/>
               <parameter name="sample-value" value="PASSED"/>
            </update>

            <get-resource plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'" pfx="sample"/>

            <exists plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'"/>

            <is-available plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'"/>

            <reserve plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'"/>

            <release plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'"/>


            <reserve plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'"/>

            <notify plugin="`$resource-plugin`" resource="sample" action="RESERVE"/>

            <delete plugin="`$resource-plugin`" resource="sample" key="sample-key == 'resourceTester.status'"/>



        </block>
    </method>

    <method rpc="configureTester" mode="sync">
        <block>
            <set>
                <parameter name='configure-plugin'
                    value='org.onap.ccsdk.sli.core.sli.provider.DummyAdaptor' />
            </set>
            <configure adaptor="`$configure-plugin`" key="dummy" activate="true">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="SUCCESS" activate="true">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="ALREADY_ACTIVE" activate="true">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="NOT_FOUND" activate="true">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="NOT_READY" activate="true">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="FAILURE" activate="true">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="dummy" activate="false">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="SUCCESS" activate="false">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="ALREADY_ACTIVE" activate="false">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="NOT_FOUND" activate="false">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="NOT_READY" activate="false">
                <parameter name="field1" value="1"/>
            </configure>
            <configure adaptor="`$configure-plugin`" key="FAILURE" activate="false">
                <parameter name="field1" value="1"/>
            </configure>

       </block>
    </method>


    <method rpc="javaPluginTester" mode="sync">
        <block>
            <set>
                <parameter name='java-plugin'
                    value='org.onap.ccsdk.sli.core.sli.provider.VoidDummyPlugin' />
            </set>
            <execute plugin="`$java-plugin`" method="dummy"/>
       </block>
    </method>

    <method rpc="allNodesTester" mode="sync">
        <block>
            <set>
                <parameter name='resource-plugin'
                    value='org.onap.ccsdk.sli.core.sli.provider.DummyResource' />
                <parameter name='configure-plugin'
                    value='org.onap.ccsdk.sli.core.sli.provider.DummyAdaptor' />
                <parameter name='java-plugin'
                    value='org.onap.ccsdk.sli.core.sli.provider.VoidDummyPlugin' />

            </set>

            <call rpc="switchTester" mode="sync" />

            <call rpc="forRecordTester" mode="sync"/>

            <call rpc="resourceTester" mode="sync"/>

            <call rpc="configureTester" mode="sync"/>

            <call rpc="javaPluginTester" mode="sync"/>

        </block>
    </method>

    <method rpc="networkCreated" mode="sync">
        <switch
            test="length($network.segment[0].provider-physical-network) >= 5 and substr($network.segment[0].provider-physical-network,0,5) == 'dvspg'">
            <outcome value="true">
                <block>
                    <set>
                        <parameter name="$vlanlist"
                            value="$network.segment[0].provider-segmentation-id" />
                    </set>
                    <for index="i" start="1" end="$network.num-segments">
                        <set>
                            <parameter name="$vlanlist"
                                value="eval($vlanlist+','+$network.segment[i].provider-segmentation-id)" />
                        </set>
                    </for>

                </block>
            </outcome>
            <outcome value="Other">
                <return status="success">
                    <parameter name="error-code" value="200" />
                </return>
            </outcome>
        </switch>
    </method>

</service-logic>

=== onap/archive-ccsdk-sli-core/sli/common/src/test/resources/expressions.xml
<service-logic xmlns='http://www.onap.org/sdnc/svclogic' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xsi:schemaLocation='http://www.onap.org/sdnc/svclogic ./svclogic.xsd' module='TEST-DG' version='1.0.0'>
	<method rpc='test-dg' mode='sync'>
		<block>
			<set>
				<parameter name='add' value='`1 + 1`' />
				<parameter name='sub' value='`2 - 1`' />
				<parameter name='div' value='`6 / 2`' />
				<parameter name='multi' value='`2 * 2`' />
				<parameter name='addDoubleQuotes' value="`1 + 1`" />
				<parameter name='subDoubleQuotes' value="`2 - 1`" />
				<parameter name='divDoubleQuotes' value="`6 / 2`" />
				<parameter name='multiDoubleQuotes' value="`2 * 2`" />
			</set>
			<set>
				<parameter name='varA' value='`$a + $b`' />
				<parameter name='varB' value='`$a + &apos;literal&apos; `' />
				<parameter name='varC' value='`&apos;literal&apos; + $b `' />
				<parameter name='varD' value='`&apos;too&apos; + &apos;literal&apos;`' />
				<parameter name='varADoubleQuotes' value="`$a + $b`" />
				<parameter name='varBDoubleQuotes' value="`$a +'literal' `" />
				<parameter name='varCDoubleQuotes' value="`'literal' + $b `" />
				<parameter name='varDDoubleQuotes' value="`'too' + 'literal'`" />
			</set>
			<set>
				<parameter name='testOne' value='`1 + 1`' />
				<parameter name='testThree' value='"1" +"1"' />
				<parameter name='testFour' value='`$portNumber + $slot + $shelf`' />
				<parameter name='testOneDoubleQuotes' value="`1 + 1`" />
				<parameter name='testThreeDoubleQuotes' value="'1' +'1'" />
				<parameter name='testFourDoubleQuotes' value="`$portNumber + $slot + $shelf`" />
			</set>
			<switch test="`'PIZZA' == 'NOTPIZZA' or $a != $b`" />
			<switch test="`'PIZZA' == 'PIZZA' and $a != $b`" />
			<switch test="`'PIZZA' == 'NOTPIZZA' or $a &gt;= $b`" />
			<switch test="`'PIZZA' == 'PIZZA' and $b &lt; $a`" />
			<switch test="`'PIZZA' == 'PIZZA'`" />
			<switch test="`$a == $b`" />
			<switch test="`'PIZZA' == 'NOTPIZZA'`" />
			<switch test="`'PIZZA' != 'PIZZA'`" />
			<switch test="`'PIZZA' != 'NOTPIZZA'`" />
			<switch test='`$a != $b`' />
			<switch test='`1 &lt; 2`' />
			<switch test='`2 &lt;= 2`' />
			<switch test='`3 &gt; 2`' />
			<switch test='`2 &gt;= 2`' />
			<switch test='$literalStartingWithDollarSign' />
			<switch test='`$dollarSignFollowedByVariableSurroundedinBackticks`' />
			<switch test='`$a == $b`' />
			<switch test="`$a == $b`" />
			<switch test='$a == $b' />
			<switch test="$a == $b" />
		</block>
	</method>
</service-logic>

=== onap/archive-ccsdk-sli-core/sli/provider/src/test/resources/clearValues.xml
<service-logic
    xmlns='http://www.onap.org/sdnc/svclogic'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.onap.org/sdnc/svclogic ./svclogic.xsd' module='TEST-DG' version='1.0.0'>
    <method rpc='test-dg' mode='sync'>
        <block>
            <set>
                <parameter name='si.field1' value='1' />
                <parameter name='si.field2' value='2' />
                <parameter name='si.field3' value='3' />
                <parameter name='si.subarray[0]' value='a' />
                <parameter name='si.subarray[1]' value='b' />
                <parameter name='si.subarray[2]' value='c' />
                <parameter name='si.subarray_length' value='3' />
                <parameter name='search1' value='6' />
                <parameter name='simonSays' value='KeepMe!' />
            </set>
            <set>
                <parameter name='si.' value='' />
            </set>
        </block>
    </method>
</service-logic>

=== onap/archive-ccsdk-sli-core/sliapi/provider/src/test/resources/sli_executeNode.xml
<!--
  ============LICENSE_START=======================================================
  openECOMP : SDN-C
  ================================================================================
  Copyright (C) 2017 AT&T Intellectual Property. All rights
  							reserved.
  ================================================================================
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  ============LICENSE_END=========================================================
-->

<service-logic xmlns="http://www.onap.org/sdnc/svclogic"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.onap.org/sdnc/svclogic ./svclogic.xsd" module="test" version="1" >

    <method rpc="executeNode" mode="sync">
        <block>
            <execute plugin="com.att.sdnctl.sli.plugin.ipAddressTools.IpAddressTool" method="getSubnetAddresses"><parameter name="ipAddress" value="`$eipam-ip-block.ip-prefix`"/><parameter name="ipVersion" value="`tmp.version`"/><parameter name="subnet" value="`$eipam-ip-block.prefix-length`"/><parameter name="ctxGateway" value="tmp.return.generate.gateway-address"/><parameter name="ctxDhcpStart" value="tmp.return.generate.dhcp-start-address"/><parameter name="ctxDhcpEnd" value="tmp.return.generate.dhcp-end-address"/><outcome value="success">
            </outcome><outcome value="Other">
            </outcome></execute>
        </block>
    </method>
</service-logic>
